name: Retrain Logistic Model Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python train_logistic.py

    - name: Commit updated model
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add model.joblib vectorizer.joblib
        git commit -m "Automated model update [skip ci]" || echo "No changes"
        git push
