name: Update Prompt Embeddings

on:
  schedule:
    - cron: '0 * * * *'   # Hourly
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    environment: secrets  # 👈 Connects to your GitHub Environment named "secrets"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run embedding script
        env:  # 👈 Set secrets at the step level (this is critical!)
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python src/embed_and_upload.py
