name: Update Prompt Embeddings

on:
  schedule:
    - cron: '0 * * * *'   # Hourly
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "SUPABASE_URL is: ${SUPABASE_URL}"
          echo "SUPABASE_KEY is: ${SUPABASE_KEY}"
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
            echo "❌ Environment variables are NOT set correctly."
            exit 1
          else
            echo "✅ Environment variables are present."
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run embedding script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python src/embed_and_upload.py
