name: Update Prompt Embeddings

on:
  schedule:
    - cron: '0 * * * *'   # Hourly
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    environment: secrets  # 👈 REQUIRED: this links to your GitHub Environment

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Export environment secrets
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run embedding script
        run: python src/embed_and_upload.py
